name: "Automatic_deployment"
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Pull
        uses: actions/checkout@v3
      - name: Connect and deployhu
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: 192.168.1.110
          username: root
          password: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            cd /https://github.com/gdut-dynamic-x/docs
            git pull