name: "Automatic_deployment"
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Pull
        uses: actions/checkout@v3
      - name: Connect and deployhu
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: 113.219.237.121
          username: dynamicx
          password: ${{ secrets.SSH_PASSWORD }}
          port: 61036
          script: |
            cd /home/dynamicx/text
            git pull